/**
 * Standard Currency Conversion Calculator
 * This API provides a range of functions to get back currency conversion rates and amounts based on current Mastercard currency conversion values.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Conversion from './Conversion';

/**
 * The ConversionRateRequest model module.
 * @module model/ConversionRateRequest
 * @version 1.0.0
 */
class ConversionRateRequest {
    /**
     * Constructs a new <code>ConversionRateRequest</code>.
     * @alias module:model/ConversionRateRequest
     */
    constructor() { 
        
        ConversionRateRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ConversionRateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConversionRateRequest} obj Optional instance to populate.
     * @return {module:model/ConversionRateRequest} The populated <code>ConversionRateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConversionRateRequest();

            if (data.hasOwnProperty('data')) {
                obj['data'] = Conversion.constructFromObject(data['data']);
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Conversion} data
 */
ConversionRateRequest.prototype['data'] = undefined;

/**
 * The date and time the API is being called in GMT.
 * @member {String} date
 */
ConversionRateRequest.prototype['date'] = undefined;

/**
 * The description of the API being called.
 * @member {String} description
 */
ConversionRateRequest.prototype['description'] = undefined;

/**
 * The name of the service being requested.
 * @member {String} name
 */
ConversionRateRequest.prototype['name'] = undefined;

/**
 * The type of response being returned by the API.
 * @member {String} type
 */
ConversionRateRequest.prototype['type'] = undefined;






export default ConversionRateRequest;

