/**
 * Standard Currency Conversion Calculator
 * This API provides a range of functions to get back currency conversion rates and amounts based on current Mastercard currency conversion values.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Currency from './Currency';

/**
 * The SettlementCurrency model module.
 * @module model/SettlementCurrency
 * @version 1.0.0
 */
class SettlementCurrency {
    /**
     * Constructs a new <code>SettlementCurrency</code>.
     * @alias module:model/SettlementCurrency
     */
    constructor() { 
        
        SettlementCurrency.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SettlementCurrency</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SettlementCurrency} obj Optional instance to populate.
     * @return {module:model/SettlementCurrency} The populated <code>SettlementCurrency</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SettlementCurrency();

            if (data.hasOwnProperty('currencies')) {
                obj['currencies'] = ApiClient.convertToType(data['currencies'], [Currency]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Currency>} currencies
 */
SettlementCurrency.prototype['currencies'] = undefined;






export default SettlementCurrency;

