/**
 * Standard Currency Conversion Calculator
 * This API provides a range of functions to get back currency conversion rates and amounts based on current Mastercard currency conversion values.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SettlementRateIssued model module.
 * @module model/SettlementRateIssued
 * @version 1.0.0
 */
class SettlementRateIssued {
    /**
     * Constructs a new <code>SettlementRateIssued</code>.
     * @alias module:model/SettlementRateIssued
     */
    constructor() { 
        
        SettlementRateIssued.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SettlementRateIssued</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SettlementRateIssued} obj Optional instance to populate.
     * @return {module:model/SettlementRateIssued} The populated <code>SettlementRateIssued</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SettlementRateIssued();

            if (data.hasOwnProperty('rateIssued')) {
                obj['rateIssued'] = ApiClient.convertToType(data['rateIssued'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The requested foreign exchange rate.
 * @member {String} rateIssued
 */
SettlementRateIssued.prototype['rateIssued'] = undefined;






export default SettlementRateIssued;

