/**
 * Standard Currency Conversion Calculator
 * This API provides a range of functions to get back currency conversion rates and amounts based on current Mastercard currency conversion values.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ConversionRateRequest from '../model/ConversionRateRequest';

/**
* ConversionRate service.
* @module api/ConversionRateApi
* @version 1.0.0
*/
export default class ConversionRateApi {

    /**
    * Constructs a new ConversionRateApi. 
    * @alias module:api/ConversionRateApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getConversionDetailUsingGET operation.
     * @callback module:api/ConversionRateApi~getConversionDetailUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ConversionRateRequest} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get the currency conversion rate details.
     * Get the currency conversion rate details.
     * @param {String} fxDate Date of the requested FX rates.
     * @param {String} transCurr Currency of the transaction.
     * @param {String} crdhldBillCurr Cardholder billing currency.
     * @param {Number} transAmt Amount in the transaction currency.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.bankFee Additional fees imposed by the bank.
     * @param {module:api/ConversionRateApi~getConversionDetailUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ConversionRateRequest}
     */
    getConversionDetailUsingGET(fxDate, transCurr, crdhldBillCurr, transAmt, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'fxDate' is set
      if (fxDate === undefined || fxDate === null) {
        throw new Error("Missing the required parameter 'fxDate' when calling getConversionDetailUsingGET");
      }
      // verify the required parameter 'transCurr' is set
      if (transCurr === undefined || transCurr === null) {
        throw new Error("Missing the required parameter 'transCurr' when calling getConversionDetailUsingGET");
      }
      // verify the required parameter 'crdhldBillCurr' is set
      if (crdhldBillCurr === undefined || crdhldBillCurr === null) {
        throw new Error("Missing the required parameter 'crdhldBillCurr' when calling getConversionDetailUsingGET");
      }
      // verify the required parameter 'transAmt' is set
      if (transAmt === undefined || transAmt === null) {
        throw new Error("Missing the required parameter 'transAmt' when calling getConversionDetailUsingGET");
      }

      let pathParams = {
      };
      let queryParams = {
        'fxDate': fxDate,
        'transCurr': transCurr,
        'crdhldBillCurr': crdhldBillCurr,
        'bankFee': opts['bankFee'],
        'transAmt': transAmt
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ConversionRateRequest;
      return this.apiClient.callApi(
        '/conversion-rate', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
