/**
 * Standard Currency Conversion Calculator
 * This API provides a range of functions to get back currency conversion rates and amounts based on current Mastercard currency conversion values.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import SettlementCurrencyRequest from '../model/SettlementCurrencyRequest';

/**
* Currencies service.
* @module api/CurrenciesApi
* @version 1.0.0
*/
export default class CurrenciesApi {

    /**
    * Constructs a new CurrenciesApi. 
    * @alias module:api/CurrenciesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getCurrencyRateDataUsingGET operation.
     * @callback module:api/CurrenciesApi~getCurrencyRateDataUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SettlementCurrencyRequest} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getCurrencyRateData
     * List of supported currencies.
     * @param {module:api/CurrenciesApi~getCurrencyRateDataUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SettlementCurrencyRequest}
     */
    getCurrencyRateDataUsingGET(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = SettlementCurrencyRequest;
      return this.apiClient.callApi(
        '/settlement-currencies', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
