/**
 * Standard Currency Conversion Calculator
 * This API provides a range of functions to get back currency conversion rates and amounts based on current Mastercard currency conversion values.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import SettlementRateIssuedRequest from '../model/SettlementRateIssuedRequest';

/**
* RateIssued service.
* @module api/RateIssuedApi
* @version 1.0.0
*/
export default class RateIssuedApi {

    /**
    * Constructs a new RateIssuedApi. 
    * @alias module:api/RateIssuedApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the isRateIssuedUsingGET operation.
     * @callback module:api/RateIssuedApi~isRateIssuedUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SettlementRateIssuedRequest} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Determine if the settlement rate has been issued.
     * Determine if the settlement rate has been issued.
     * @param {Object} opts Optional parameters
     * @param {String} opts.date The date by which the rate would have been issued.
     * @param {module:api/RateIssuedApi~isRateIssuedUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SettlementRateIssuedRequest}
     */
    isRateIssuedUsingGET(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'date': opts['date']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = SettlementRateIssuedRequest;
      return this.apiClient.callApi(
        '/conversion-rate-issued', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
